<?php

/**
 * Implements hook_install().
 */
function starter_admin_install() {
  $admin_theme = 'shiny';

  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', $admin_theme)
    ->execute();

  db_update('system')
    ->fields(array('weight' => 999))
    ->condition('type', 'module')
    ->condition('name', 'starter_admin')
    ->execute();
}
