core = "7.x"
api = "2"

projects[] = "shiny"

projects[backup_migrate][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[views_bulk_operations][subdir] = "contrib"
projects[environment_indicator][subdir] = "contrib"
projects[admin_views][subdir] = "contrib"
projects[admin_language][subdir] = "contrib"
projects[fpa][subdir] = "contrib"
projects[ultimate_cron][subdir] = "contrib"
projects[navbar][subdir] = "navbar"

libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "https://github.com/jashkenas/backbone/archive/1.0.0.zip"
libraries[underscore][download][type] = "file"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore/archive/master.zip"
libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/v2.7.1.zip"
