core = "7.x"
api = "2"

projects[] = "shiny"

projects[backup_migrate][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[views_bulk_operations][subdir] = "contrib"
projects[environment_indicator][subdir] = "contrib"
projects[admin_views][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[admin_language][subdir] = "contrib"
projects[fpa][subdir] = "contrib"
projects[ultimate_cron][subdir] = "contrib"
projects[editablefields][subdir] = "contrib"
projects[editablefields_as_link][subdir] = "contrib"
